/*
Goodsender API

Testing DomainsAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package goodsender

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	goodsender "github.com/good-sender/go-sdk"
)

func Test_goodsender_DomainsAPIService(t *testing.T) {

	configuration := goodsender.NewConfiguration()
	apiClient := goodsender.NewAPIClient(configuration)

	t.Run("Test DomainsAPIService ListDomains", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.DomainsAPI.ListDomains(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
