/*
Goodsender API

Goodsender API. ### Authorization  All API requests require an API key in the `Authorization` header:  ``` Authorization: Bearer <your-api-key> ``` 

API version: 1.0.0
Contact: support@goodsender.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package goodsender

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the DomainListResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DomainListResponse{}

// DomainListResponse struct for DomainListResponse
type DomainListResponse struct {
	Domains []Domain `json:"domains"`
	// Cursor to retrieve the next page of results. Omitted if there are no more results.
	NextCursor *string `json:"nextCursor,omitempty"`
}

type _DomainListResponse DomainListResponse

// NewDomainListResponse instantiates a new DomainListResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDomainListResponse(domains []Domain) *DomainListResponse {
	this := DomainListResponse{}
	this.Domains = domains
	return &this
}

// NewDomainListResponseWithDefaults instantiates a new DomainListResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDomainListResponseWithDefaults() *DomainListResponse {
	this := DomainListResponse{}
	return &this
}

// GetDomains returns the Domains field value
func (o *DomainListResponse) GetDomains() []Domain {
	if o == nil {
		var ret []Domain
		return ret
	}

	return o.Domains
}

// GetDomainsOk returns a tuple with the Domains field value
// and a boolean to check if the value has been set.
func (o *DomainListResponse) GetDomainsOk() ([]Domain, bool) {
	if o == nil {
		return nil, false
	}
	return o.Domains, true
}

// SetDomains sets field value
func (o *DomainListResponse) SetDomains(v []Domain) {
	o.Domains = v
}

// GetNextCursor returns the NextCursor field value if set, zero value otherwise.
func (o *DomainListResponse) GetNextCursor() string {
	if o == nil || IsNil(o.NextCursor) {
		var ret string
		return ret
	}
	return *o.NextCursor
}

// GetNextCursorOk returns a tuple with the NextCursor field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *DomainListResponse) GetNextCursorOk() (*string, bool) {
	if o == nil || IsNil(o.NextCursor) {
		return nil, false
	}
	return o.NextCursor, true
}

// HasNextCursor returns a boolean if a field has been set.
func (o *DomainListResponse) HasNextCursor() bool {
	if o != nil && !IsNil(o.NextCursor) {
		return true
	}

	return false
}

// SetNextCursor gets a reference to the given string and assigns it to the NextCursor field.
func (o *DomainListResponse) SetNextCursor(v string) {
	o.NextCursor = &v
}

func (o DomainListResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DomainListResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["domains"] = o.Domains
	if !IsNil(o.NextCursor) {
		toSerialize["nextCursor"] = o.NextCursor
	}
	return toSerialize, nil
}

func (o *DomainListResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"domains",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDomainListResponse := _DomainListResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDomainListResponse)

	if err != nil {
		return err
	}

	*o = DomainListResponse(varDomainListResponse)

	return err
}

type NullableDomainListResponse struct {
	value *DomainListResponse
	isSet bool
}

func (v NullableDomainListResponse) Get() *DomainListResponse {
	return v.value
}

func (v *NullableDomainListResponse) Set(val *DomainListResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableDomainListResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableDomainListResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDomainListResponse(val *DomainListResponse) *NullableDomainListResponse {
	return &NullableDomainListResponse{value: val, isSet: true}
}

func (v NullableDomainListResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDomainListResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


