/*
Goodsender API

Goodsender API. ### Authorization  All API requests require an API key in the `Authorization` header:  ``` Authorization: Bearer <your-api-key> ``` 

API version: 1.0.0
Contact: support@goodsender.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package goodsender

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the TemplateEmailRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TemplateEmailRequest{}

// TemplateEmailRequest struct for TemplateEmailRequest
type TemplateEmailRequest struct {
	// Sender address (required)
	From Address `json:"from"`
	// Recipient address (required)
	To Address `json:"to"`
	// The subject of the email (required)
	Subject string `json:"subject"`
	Template TemplateEmailRequestTemplate `json:"template"`
}

type _TemplateEmailRequest TemplateEmailRequest

// NewTemplateEmailRequest instantiates a new TemplateEmailRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTemplateEmailRequest(from Address, to Address, subject string, template TemplateEmailRequestTemplate) *TemplateEmailRequest {
	this := TemplateEmailRequest{}
	this.From = from
	this.To = to
	this.Subject = subject
	this.Template = template
	return &this
}

// NewTemplateEmailRequestWithDefaults instantiates a new TemplateEmailRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTemplateEmailRequestWithDefaults() *TemplateEmailRequest {
	this := TemplateEmailRequest{}
	return &this
}

// GetFrom returns the From field value
func (o *TemplateEmailRequest) GetFrom() Address {
	if o == nil {
		var ret Address
		return ret
	}

	return o.From
}

// GetFromOk returns a tuple with the From field value
// and a boolean to check if the value has been set.
func (o *TemplateEmailRequest) GetFromOk() (*Address, bool) {
	if o == nil {
		return nil, false
	}
	return &o.From, true
}

// SetFrom sets field value
func (o *TemplateEmailRequest) SetFrom(v Address) {
	o.From = v
}

// GetTo returns the To field value
func (o *TemplateEmailRequest) GetTo() Address {
	if o == nil {
		var ret Address
		return ret
	}

	return o.To
}

// GetToOk returns a tuple with the To field value
// and a boolean to check if the value has been set.
func (o *TemplateEmailRequest) GetToOk() (*Address, bool) {
	if o == nil {
		return nil, false
	}
	return &o.To, true
}

// SetTo sets field value
func (o *TemplateEmailRequest) SetTo(v Address) {
	o.To = v
}

// GetSubject returns the Subject field value
func (o *TemplateEmailRequest) GetSubject() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Subject
}

// GetSubjectOk returns a tuple with the Subject field value
// and a boolean to check if the value has been set.
func (o *TemplateEmailRequest) GetSubjectOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Subject, true
}

// SetSubject sets field value
func (o *TemplateEmailRequest) SetSubject(v string) {
	o.Subject = v
}

// GetTemplate returns the Template field value
func (o *TemplateEmailRequest) GetTemplate() TemplateEmailRequestTemplate {
	if o == nil {
		var ret TemplateEmailRequestTemplate
		return ret
	}

	return o.Template
}

// GetTemplateOk returns a tuple with the Template field value
// and a boolean to check if the value has been set.
func (o *TemplateEmailRequest) GetTemplateOk() (*TemplateEmailRequestTemplate, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Template, true
}

// SetTemplate sets field value
func (o *TemplateEmailRequest) SetTemplate(v TemplateEmailRequestTemplate) {
	o.Template = v
}

func (o TemplateEmailRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TemplateEmailRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["from"] = o.From
	toSerialize["to"] = o.To
	toSerialize["subject"] = o.Subject
	toSerialize["template"] = o.Template
	return toSerialize, nil
}

func (o *TemplateEmailRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"from",
		"to",
		"subject",
		"template",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTemplateEmailRequest := _TemplateEmailRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varTemplateEmailRequest)

	if err != nil {
		return err
	}

	*o = TemplateEmailRequest(varTemplateEmailRequest)

	return err
}

type NullableTemplateEmailRequest struct {
	value *TemplateEmailRequest
	isSet bool
}

func (v NullableTemplateEmailRequest) Get() *TemplateEmailRequest {
	return v.value
}

func (v *NullableTemplateEmailRequest) Set(val *TemplateEmailRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableTemplateEmailRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableTemplateEmailRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTemplateEmailRequest(val *TemplateEmailRequest) *NullableTemplateEmailRequest {
	return &NullableTemplateEmailRequest{value: val, isSet: true}
}

func (v NullableTemplateEmailRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTemplateEmailRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


