/*
Goodsender API

Goodsender API. ### Authorization  All API requests require an API key in the `Authorization` header:  ``` Authorization: Bearer <your-api-key> ``` 

API version: 1.0.0
Contact: support@goodsender.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package goodsender

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ConsentEmailRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ConsentEmailRequest{}

// ConsentEmailRequest struct for ConsentEmailRequest
type ConsentEmailRequest struct {
	// Domain for the email addresses.
	Domain string `json:"domain"`
	// URL to which the user will be redirected after providing consent. {email} in the URL will be replaced with the recipient's email address.
	RedirectUrl *string `json:"redirect_url,omitempty"`
	// Recipients to request consent from. Each entry may be either a plain email string or a `{ email, name? }` object so callers can attach a display name to a specific recipient. Mixing the two forms in one request is allowed. 
	Emails []ConsentEmailEntry `json:"emails"`
}

type _ConsentEmailRequest ConsentEmailRequest

// NewConsentEmailRequest instantiates a new ConsentEmailRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewConsentEmailRequest(domain string, emails []ConsentEmailEntry) *ConsentEmailRequest {
	this := ConsentEmailRequest{}
	this.Domain = domain
	this.Emails = emails
	return &this
}

// NewConsentEmailRequestWithDefaults instantiates a new ConsentEmailRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewConsentEmailRequestWithDefaults() *ConsentEmailRequest {
	this := ConsentEmailRequest{}
	return &this
}

// GetDomain returns the Domain field value
func (o *ConsentEmailRequest) GetDomain() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Domain
}

// GetDomainOk returns a tuple with the Domain field value
// and a boolean to check if the value has been set.
func (o *ConsentEmailRequest) GetDomainOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Domain, true
}

// SetDomain sets field value
func (o *ConsentEmailRequest) SetDomain(v string) {
	o.Domain = v
}

// GetRedirectUrl returns the RedirectUrl field value if set, zero value otherwise.
func (o *ConsentEmailRequest) GetRedirectUrl() string {
	if o == nil || IsNil(o.RedirectUrl) {
		var ret string
		return ret
	}
	return *o.RedirectUrl
}

// GetRedirectUrlOk returns a tuple with the RedirectUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ConsentEmailRequest) GetRedirectUrlOk() (*string, bool) {
	if o == nil || IsNil(o.RedirectUrl) {
		return nil, false
	}
	return o.RedirectUrl, true
}

// HasRedirectUrl returns a boolean if a field has been set.
func (o *ConsentEmailRequest) HasRedirectUrl() bool {
	if o != nil && !IsNil(o.RedirectUrl) {
		return true
	}

	return false
}

// SetRedirectUrl gets a reference to the given string and assigns it to the RedirectUrl field.
func (o *ConsentEmailRequest) SetRedirectUrl(v string) {
	o.RedirectUrl = &v
}

// GetEmails returns the Emails field value
func (o *ConsentEmailRequest) GetEmails() []ConsentEmailEntry {
	if o == nil {
		var ret []ConsentEmailEntry
		return ret
	}

	return o.Emails
}

// GetEmailsOk returns a tuple with the Emails field value
// and a boolean to check if the value has been set.
func (o *ConsentEmailRequest) GetEmailsOk() ([]ConsentEmailEntry, bool) {
	if o == nil {
		return nil, false
	}
	return o.Emails, true
}

// SetEmails sets field value
func (o *ConsentEmailRequest) SetEmails(v []ConsentEmailEntry) {
	o.Emails = v
}

func (o ConsentEmailRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ConsentEmailRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["domain"] = o.Domain
	if !IsNil(o.RedirectUrl) {
		toSerialize["redirect_url"] = o.RedirectUrl
	}
	toSerialize["emails"] = o.Emails
	return toSerialize, nil
}

func (o *ConsentEmailRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"domain",
		"emails",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varConsentEmailRequest := _ConsentEmailRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varConsentEmailRequest)

	if err != nil {
		return err
	}

	*o = ConsentEmailRequest(varConsentEmailRequest)

	return err
}

type NullableConsentEmailRequest struct {
	value *ConsentEmailRequest
	isSet bool
}

func (v NullableConsentEmailRequest) Get() *ConsentEmailRequest {
	return v.value
}

func (v *NullableConsentEmailRequest) Set(val *ConsentEmailRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableConsentEmailRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableConsentEmailRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableConsentEmailRequest(val *ConsentEmailRequest) *NullableConsentEmailRequest {
	return &NullableConsentEmailRequest{value: val, isSet: true}
}

func (v NullableConsentEmailRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableConsentEmailRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


