/*
Goodsender API

Goodsender API. ### Authorization  All API requests require an API key in the `Authorization` header:  ``` Authorization: Bearer <your-api-key> ``` 

API version: 1.0.0
Contact: support@goodsender.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package goodsender

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the EmailListResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EmailListResponse{}

// EmailListResponse struct for EmailListResponse
type EmailListResponse struct {
	Emails []EmailAccount `json:"emails"`
	// Cursor to retrieve the next page of results. Omitted if there are no more results.
	NextCursor *string `json:"nextCursor,omitempty"`
}

type _EmailListResponse EmailListResponse

// NewEmailListResponse instantiates a new EmailListResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEmailListResponse(emails []EmailAccount) *EmailListResponse {
	this := EmailListResponse{}
	this.Emails = emails
	return &this
}

// NewEmailListResponseWithDefaults instantiates a new EmailListResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEmailListResponseWithDefaults() *EmailListResponse {
	this := EmailListResponse{}
	return &this
}

// GetEmails returns the Emails field value
func (o *EmailListResponse) GetEmails() []EmailAccount {
	if o == nil {
		var ret []EmailAccount
		return ret
	}

	return o.Emails
}

// GetEmailsOk returns a tuple with the Emails field value
// and a boolean to check if the value has been set.
func (o *EmailListResponse) GetEmailsOk() ([]EmailAccount, bool) {
	if o == nil {
		return nil, false
	}
	return o.Emails, true
}

// SetEmails sets field value
func (o *EmailListResponse) SetEmails(v []EmailAccount) {
	o.Emails = v
}

// GetNextCursor returns the NextCursor field value if set, zero value otherwise.
func (o *EmailListResponse) GetNextCursor() string {
	if o == nil || IsNil(o.NextCursor) {
		var ret string
		return ret
	}
	return *o.NextCursor
}

// GetNextCursorOk returns a tuple with the NextCursor field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EmailListResponse) GetNextCursorOk() (*string, bool) {
	if o == nil || IsNil(o.NextCursor) {
		return nil, false
	}
	return o.NextCursor, true
}

// HasNextCursor returns a boolean if a field has been set.
func (o *EmailListResponse) HasNextCursor() bool {
	if o != nil && !IsNil(o.NextCursor) {
		return true
	}

	return false
}

// SetNextCursor gets a reference to the given string and assigns it to the NextCursor field.
func (o *EmailListResponse) SetNextCursor(v string) {
	o.NextCursor = &v
}

func (o EmailListResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EmailListResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["emails"] = o.Emails
	if !IsNil(o.NextCursor) {
		toSerialize["nextCursor"] = o.NextCursor
	}
	return toSerialize, nil
}

func (o *EmailListResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"emails",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varEmailListResponse := _EmailListResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varEmailListResponse)

	if err != nil {
		return err
	}

	*o = EmailListResponse(varEmailListResponse)

	return err
}

type NullableEmailListResponse struct {
	value *EmailListResponse
	isSet bool
}

func (v NullableEmailListResponse) Get() *EmailListResponse {
	return v.value
}

func (v *NullableEmailListResponse) Set(val *EmailListResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableEmailListResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableEmailListResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEmailListResponse(val *EmailListResponse) *NullableEmailListResponse {
	return &NullableEmailListResponse{value: val, isSet: true}
}

func (v NullableEmailListResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEmailListResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


