/*
Goodsender API

Goodsender API. ### Authorization  All API requests require an API key in the `Authorization` header:  ``` Authorization: Bearer <your-api-key> ``` 

API version: 1.0.0
Contact: support@goodsender.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package goodsender

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SendEmailResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SendEmailResponse{}

// SendEmailResponse struct for SendEmailResponse
type SendEmailResponse struct {
	// Number of emails sent (recipients had consent allowing delivery)
	Sent int32 `json:"sent"`
	// Number of emails not sent because recipients did not have granted consent to receive emails
	Declined int32 `json:"declined"`
}

type _SendEmailResponse SendEmailResponse

// NewSendEmailResponse instantiates a new SendEmailResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSendEmailResponse(sent int32, declined int32) *SendEmailResponse {
	this := SendEmailResponse{}
	this.Sent = sent
	this.Declined = declined
	return &this
}

// NewSendEmailResponseWithDefaults instantiates a new SendEmailResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSendEmailResponseWithDefaults() *SendEmailResponse {
	this := SendEmailResponse{}
	return &this
}

// GetSent returns the Sent field value
func (o *SendEmailResponse) GetSent() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Sent
}

// GetSentOk returns a tuple with the Sent field value
// and a boolean to check if the value has been set.
func (o *SendEmailResponse) GetSentOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Sent, true
}

// SetSent sets field value
func (o *SendEmailResponse) SetSent(v int32) {
	o.Sent = v
}

// GetDeclined returns the Declined field value
func (o *SendEmailResponse) GetDeclined() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Declined
}

// GetDeclinedOk returns a tuple with the Declined field value
// and a boolean to check if the value has been set.
func (o *SendEmailResponse) GetDeclinedOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Declined, true
}

// SetDeclined sets field value
func (o *SendEmailResponse) SetDeclined(v int32) {
	o.Declined = v
}

func (o SendEmailResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SendEmailResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["sent"] = o.Sent
	toSerialize["declined"] = o.Declined
	return toSerialize, nil
}

func (o *SendEmailResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"sent",
		"declined",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSendEmailResponse := _SendEmailResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSendEmailResponse)

	if err != nil {
		return err
	}

	*o = SendEmailResponse(varSendEmailResponse)

	return err
}

type NullableSendEmailResponse struct {
	value *SendEmailResponse
	isSet bool
}

func (v NullableSendEmailResponse) Get() *SendEmailResponse {
	return v.value
}

func (v *NullableSendEmailResponse) Set(val *SendEmailResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableSendEmailResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableSendEmailResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSendEmailResponse(val *SendEmailResponse) *NullableSendEmailResponse {
	return &NullableSendEmailResponse{value: val, isSet: true}
}

func (v NullableSendEmailResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSendEmailResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


