/*
Goodsender API

Goodsender API. ### Authorization  All API requests require an API key in the `Authorization` header:  ``` Authorization: Bearer <your-api-key> ``` 

API version: 1.0.0
Contact: support@goodsender.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package goodsender

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the Attachment type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Attachment{}

// Attachment Either inline_id or file_name is required. Content must be base64 encoded.
type Attachment struct {
	// File name for the attachment
	FileName *string `json:"file_name,omitempty"`
	// Base64 encoded content
	Content *string `json:"content,omitempty"`
	// MIME content type (required)
	ContentType string `json:"content_type"`
	// Inline attachment ID
	InlineId *string `json:"inline_id,omitempty"`
}

type _Attachment Attachment

// NewAttachment instantiates a new Attachment object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAttachment(contentType string) *Attachment {
	this := Attachment{}
	var fileName string = ""
	this.FileName = &fileName
	this.ContentType = contentType
	var inlineId string = ""
	this.InlineId = &inlineId
	return &this
}

// NewAttachmentWithDefaults instantiates a new Attachment object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAttachmentWithDefaults() *Attachment {
	this := Attachment{}
	var fileName string = ""
	this.FileName = &fileName
	var contentType string = ""
	this.ContentType = contentType
	var inlineId string = ""
	this.InlineId = &inlineId
	return &this
}

// GetFileName returns the FileName field value if set, zero value otherwise.
func (o *Attachment) GetFileName() string {
	if o == nil || IsNil(o.FileName) {
		var ret string
		return ret
	}
	return *o.FileName
}

// GetFileNameOk returns a tuple with the FileName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Attachment) GetFileNameOk() (*string, bool) {
	if o == nil || IsNil(o.FileName) {
		return nil, false
	}
	return o.FileName, true
}

// HasFileName returns a boolean if a field has been set.
func (o *Attachment) HasFileName() bool {
	if o != nil && !IsNil(o.FileName) {
		return true
	}

	return false
}

// SetFileName gets a reference to the given string and assigns it to the FileName field.
func (o *Attachment) SetFileName(v string) {
	o.FileName = &v
}

// GetContent returns the Content field value if set, zero value otherwise.
func (o *Attachment) GetContent() string {
	if o == nil || IsNil(o.Content) {
		var ret string
		return ret
	}
	return *o.Content
}

// GetContentOk returns a tuple with the Content field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Attachment) GetContentOk() (*string, bool) {
	if o == nil || IsNil(o.Content) {
		return nil, false
	}
	return o.Content, true
}

// HasContent returns a boolean if a field has been set.
func (o *Attachment) HasContent() bool {
	if o != nil && !IsNil(o.Content) {
		return true
	}

	return false
}

// SetContent gets a reference to the given string and assigns it to the Content field.
func (o *Attachment) SetContent(v string) {
	o.Content = &v
}

// GetContentType returns the ContentType field value
func (o *Attachment) GetContentType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ContentType
}

// GetContentTypeOk returns a tuple with the ContentType field value
// and a boolean to check if the value has been set.
func (o *Attachment) GetContentTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ContentType, true
}

// SetContentType sets field value
func (o *Attachment) SetContentType(v string) {
	o.ContentType = v
}

// GetInlineId returns the InlineId field value if set, zero value otherwise.
func (o *Attachment) GetInlineId() string {
	if o == nil || IsNil(o.InlineId) {
		var ret string
		return ret
	}
	return *o.InlineId
}

// GetInlineIdOk returns a tuple with the InlineId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Attachment) GetInlineIdOk() (*string, bool) {
	if o == nil || IsNil(o.InlineId) {
		return nil, false
	}
	return o.InlineId, true
}

// HasInlineId returns a boolean if a field has been set.
func (o *Attachment) HasInlineId() bool {
	if o != nil && !IsNil(o.InlineId) {
		return true
	}

	return false
}

// SetInlineId gets a reference to the given string and assigns it to the InlineId field.
func (o *Attachment) SetInlineId(v string) {
	o.InlineId = &v
}

func (o Attachment) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Attachment) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.FileName) {
		toSerialize["file_name"] = o.FileName
	}
	if !IsNil(o.Content) {
		toSerialize["content"] = o.Content
	}
	toSerialize["content_type"] = o.ContentType
	if !IsNil(o.InlineId) {
		toSerialize["inline_id"] = o.InlineId
	}
	return toSerialize, nil
}

func (o *Attachment) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"content_type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAttachment := _Attachment{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAttachment)

	if err != nil {
		return err
	}

	*o = Attachment(varAttachment)

	return err
}

type NullableAttachment struct {
	value *Attachment
	isSet bool
}

func (v NullableAttachment) Get() *Attachment {
	return v.value
}

func (v *NullableAttachment) Set(val *Attachment) {
	v.value = val
	v.isSet = true
}

func (v NullableAttachment) IsSet() bool {
	return v.isSet
}

func (v *NullableAttachment) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAttachment(val *Attachment) *NullableAttachment {
	return &NullableAttachment{value: val, isSet: true}
}

func (v NullableAttachment) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAttachment) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


