/*
Goodsender API

Goodsender API. ### Authorization  All API requests require an API key in the `Authorization` header:  ``` Authorization: Bearer <your-api-key> ``` 

API version: 1.0.0
Contact: support@goodsender.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package goodsender

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the Domain type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Domain{}

// Domain struct for Domain
type Domain struct {
	// The domain name.
	Domain string `json:"domain"`
	// Subdomain used for click tracking.
	Tracking string `json:"tracking"`
	// Subdomain used for the return path.
	ReturnPath string `json:"return_path"`
	// Whether outbound mail from this domain must be sent over TLS.
	RequireTls bool `json:"require_tls"`
	Verification DomainVerification `json:"verification"`
}

type _Domain Domain

// NewDomain instantiates a new Domain object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDomain(domain string, tracking string, returnPath string, requireTls bool, verification DomainVerification) *Domain {
	this := Domain{}
	this.Domain = domain
	this.Tracking = tracking
	this.ReturnPath = returnPath
	this.RequireTls = requireTls
	this.Verification = verification
	return &this
}

// NewDomainWithDefaults instantiates a new Domain object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDomainWithDefaults() *Domain {
	this := Domain{}
	return &this
}

// GetDomain returns the Domain field value
func (o *Domain) GetDomain() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Domain
}

// GetDomainOk returns a tuple with the Domain field value
// and a boolean to check if the value has been set.
func (o *Domain) GetDomainOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Domain, true
}

// SetDomain sets field value
func (o *Domain) SetDomain(v string) {
	o.Domain = v
}

// GetTracking returns the Tracking field value
func (o *Domain) GetTracking() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Tracking
}

// GetTrackingOk returns a tuple with the Tracking field value
// and a boolean to check if the value has been set.
func (o *Domain) GetTrackingOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Tracking, true
}

// SetTracking sets field value
func (o *Domain) SetTracking(v string) {
	o.Tracking = v
}

// GetReturnPath returns the ReturnPath field value
func (o *Domain) GetReturnPath() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ReturnPath
}

// GetReturnPathOk returns a tuple with the ReturnPath field value
// and a boolean to check if the value has been set.
func (o *Domain) GetReturnPathOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ReturnPath, true
}

// SetReturnPath sets field value
func (o *Domain) SetReturnPath(v string) {
	o.ReturnPath = v
}

// GetRequireTls returns the RequireTls field value
func (o *Domain) GetRequireTls() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.RequireTls
}

// GetRequireTlsOk returns a tuple with the RequireTls field value
// and a boolean to check if the value has been set.
func (o *Domain) GetRequireTlsOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RequireTls, true
}

// SetRequireTls sets field value
func (o *Domain) SetRequireTls(v bool) {
	o.RequireTls = v
}

// GetVerification returns the Verification field value
func (o *Domain) GetVerification() DomainVerification {
	if o == nil {
		var ret DomainVerification
		return ret
	}

	return o.Verification
}

// GetVerificationOk returns a tuple with the Verification field value
// and a boolean to check if the value has been set.
func (o *Domain) GetVerificationOk() (*DomainVerification, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Verification, true
}

// SetVerification sets field value
func (o *Domain) SetVerification(v DomainVerification) {
	o.Verification = v
}

func (o Domain) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Domain) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["domain"] = o.Domain
	toSerialize["tracking"] = o.Tracking
	toSerialize["return_path"] = o.ReturnPath
	toSerialize["require_tls"] = o.RequireTls
	toSerialize["verification"] = o.Verification
	return toSerialize, nil
}

func (o *Domain) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"domain",
		"tracking",
		"return_path",
		"require_tls",
		"verification",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDomain := _Domain{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDomain)

	if err != nil {
		return err
	}

	*o = Domain(varDomain)

	return err
}

type NullableDomain struct {
	value *Domain
	isSet bool
}

func (v NullableDomain) Get() *Domain {
	return v.value
}

func (v *NullableDomain) Set(val *Domain) {
	v.value = val
	v.isSet = true
}

func (v NullableDomain) IsSet() bool {
	return v.isSet
}

func (v *NullableDomain) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDomain(val *Domain) *NullableDomain {
	return &NullableDomain{value: val, isSet: true}
}

func (v NullableDomain) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDomain) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


