/*
Goodsender API

Goodsender API. ### Authorization  All API requests require an API key in the `Authorization` header:  ``` Authorization: Bearer <your-api-key> ``` 

API version: 1.0.0
Contact: support@goodsender.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package goodsender

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ConsentEmailRecipient type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ConsentEmailRecipient{}

// ConsentEmailRecipient Recipient envelope with optional display name. Pass this shape instead of a bare email string when you want the name to appear in the To header on the consent email and in subsequent listings.
type ConsentEmailRecipient struct {
	// Recipient email address. Leading and trailing whitespace are stripped server-side.
	Email string `json:"email"`
	// Optional display name. Pass a non-empty string to set or replace the stored name. Passing `null`, an empty string, or omitting the field on a re-submitted recipient leaves any previously-stored name unchanged — clearing must be done via the dashboard / authenticated edit flow. 
	Name NullableString `json:"name,omitempty"`
}

type _ConsentEmailRecipient ConsentEmailRecipient

// NewConsentEmailRecipient instantiates a new ConsentEmailRecipient object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewConsentEmailRecipient(email string) *ConsentEmailRecipient {
	this := ConsentEmailRecipient{}
	this.Email = email
	return &this
}

// NewConsentEmailRecipientWithDefaults instantiates a new ConsentEmailRecipient object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewConsentEmailRecipientWithDefaults() *ConsentEmailRecipient {
	this := ConsentEmailRecipient{}
	return &this
}

// GetEmail returns the Email field value
func (o *ConsentEmailRecipient) GetEmail() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Email
}

// GetEmailOk returns a tuple with the Email field value
// and a boolean to check if the value has been set.
func (o *ConsentEmailRecipient) GetEmailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Email, true
}

// SetEmail sets field value
func (o *ConsentEmailRecipient) SetEmail(v string) {
	o.Email = v
}

// GetName returns the Name field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *ConsentEmailRecipient) GetName() string {
	if o == nil || IsNil(o.Name.Get()) {
		var ret string
		return ret
	}
	return *o.Name.Get()
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ConsentEmailRecipient) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Name.Get(), o.Name.IsSet()
}

// HasName returns a boolean if a field has been set.
func (o *ConsentEmailRecipient) HasName() bool {
	if o != nil && o.Name.IsSet() {
		return true
	}

	return false
}

// SetName gets a reference to the given NullableString and assigns it to the Name field.
func (o *ConsentEmailRecipient) SetName(v string) {
	o.Name.Set(&v)
}
// SetNameNil sets the value for Name to be an explicit nil
func (o *ConsentEmailRecipient) SetNameNil() {
	o.Name.Set(nil)
}

// UnsetName ensures that no value is present for Name, not even an explicit nil
func (o *ConsentEmailRecipient) UnsetName() {
	o.Name.Unset()
}

func (o ConsentEmailRecipient) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ConsentEmailRecipient) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["email"] = o.Email
	if o.Name.IsSet() {
		toSerialize["name"] = o.Name.Get()
	}
	return toSerialize, nil
}

func (o *ConsentEmailRecipient) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"email",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varConsentEmailRecipient := _ConsentEmailRecipient{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varConsentEmailRecipient)

	if err != nil {
		return err
	}

	*o = ConsentEmailRecipient(varConsentEmailRecipient)

	return err
}

type NullableConsentEmailRecipient struct {
	value *ConsentEmailRecipient
	isSet bool
}

func (v NullableConsentEmailRecipient) Get() *ConsentEmailRecipient {
	return v.value
}

func (v *NullableConsentEmailRecipient) Set(val *ConsentEmailRecipient) {
	v.value = val
	v.isSet = true
}

func (v NullableConsentEmailRecipient) IsSet() bool {
	return v.isSet
}

func (v *NullableConsentEmailRecipient) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableConsentEmailRecipient(val *ConsentEmailRecipient) *NullableConsentEmailRecipient {
	return &NullableConsentEmailRecipient{value: val, isSet: true}
}

func (v NullableConsentEmailRecipient) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableConsentEmailRecipient) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


