/*
Goodsender API

Goodsender API. ### Authorization  All API requests require an API key in the `Authorization` header:  ``` Authorization: Bearer <your-api-key> ``` 

API version: 1.0.0
Contact: support@goodsender.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package goodsender

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SendEmail type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SendEmail{}

// SendEmail Must provide valid sender and subject. At least one recipient (from 'to', 'cc', or 'bcc') is required. Either 'text_content', 'html_content', 'markdown_content', or 'template_id' is required. When 'markdown_content' is provided, 'text_content' and 'html_content' are ignored. 
type SendEmail struct {
	// Sender address (required)
	From Address `json:"from"`
	// To recipients. At least one recipient (to, cc, or bcc) is required. Maximum 1000 recipients per email.
	To []Address `json:"to"`
	// The subject of the email (required)
	Subject string `json:"subject"`
	// Plain text content
	TextContent *string `json:"text_content,omitempty"`
	// HTML content
	HtmlContent *string `json:"html_content,omitempty"`
	// Markdown content. When provided, text_content and html_content are ignored. The raw markdown is used as text_content and rendered to HTML for html_content. 
	MarkdownContent *string `json:"markdown_content,omitempty"`
	// Template ID for templated emails
	TemplateId *string `json:"template_id,omitempty"`
	// Data to populate template variables
	TemplateData map[string]interface{} `json:"template_data,omitempty"`
	// Email attachments
	Attachments []Attachment `json:"attachments,omitempty"`
	// Custom email headers
	Headers map[string]string `json:"headers,omitempty"`
	// Reply-to address
	ReplyTo *Address `json:"reply_to,omitempty"`
	// Unix timestamp for when to send the email. Must not be more than 72 hours in the future. If 0, sends immediately.
	SendTime *int64 `json:"send_time,omitempty"`
	// Custom data to include in webhook events. Maximum 10 keys, key length 50 chars, value length 100 chars.
	WebhookData map[string]string `json:"webhook_data,omitempty"`
	// Custom tag for tracking. Maximum 100 characters.
	Tag *string `json:"tag,omitempty"`
	// Email tracking settings
	Tracking *TrackingSettings `json:"tracking,omitempty"`
}

type _SendEmail SendEmail

// NewSendEmail instantiates a new SendEmail object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSendEmail(from Address, to []Address, subject string) *SendEmail {
	this := SendEmail{}
	this.From = from
	this.To = to
	this.Subject = subject
	return &this
}

// NewSendEmailWithDefaults instantiates a new SendEmail object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSendEmailWithDefaults() *SendEmail {
	this := SendEmail{}
	var subject string = ""
	this.Subject = subject
	return &this
}

// GetFrom returns the From field value
func (o *SendEmail) GetFrom() Address {
	if o == nil {
		var ret Address
		return ret
	}

	return o.From
}

// GetFromOk returns a tuple with the From field value
// and a boolean to check if the value has been set.
func (o *SendEmail) GetFromOk() (*Address, bool) {
	if o == nil {
		return nil, false
	}
	return &o.From, true
}

// SetFrom sets field value
func (o *SendEmail) SetFrom(v Address) {
	o.From = v
}

// GetTo returns the To field value
func (o *SendEmail) GetTo() []Address {
	if o == nil {
		var ret []Address
		return ret
	}

	return o.To
}

// GetToOk returns a tuple with the To field value
// and a boolean to check if the value has been set.
func (o *SendEmail) GetToOk() ([]Address, bool) {
	if o == nil {
		return nil, false
	}
	return o.To, true
}

// SetTo sets field value
func (o *SendEmail) SetTo(v []Address) {
	o.To = v
}

// GetSubject returns the Subject field value
func (o *SendEmail) GetSubject() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Subject
}

// GetSubjectOk returns a tuple with the Subject field value
// and a boolean to check if the value has been set.
func (o *SendEmail) GetSubjectOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Subject, true
}

// SetSubject sets field value
func (o *SendEmail) SetSubject(v string) {
	o.Subject = v
}

// GetTextContent returns the TextContent field value if set, zero value otherwise.
func (o *SendEmail) GetTextContent() string {
	if o == nil || IsNil(o.TextContent) {
		var ret string
		return ret
	}
	return *o.TextContent
}

// GetTextContentOk returns a tuple with the TextContent field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SendEmail) GetTextContentOk() (*string, bool) {
	if o == nil || IsNil(o.TextContent) {
		return nil, false
	}
	return o.TextContent, true
}

// HasTextContent returns a boolean if a field has been set.
func (o *SendEmail) HasTextContent() bool {
	if o != nil && !IsNil(o.TextContent) {
		return true
	}

	return false
}

// SetTextContent gets a reference to the given string and assigns it to the TextContent field.
func (o *SendEmail) SetTextContent(v string) {
	o.TextContent = &v
}

// GetHtmlContent returns the HtmlContent field value if set, zero value otherwise.
func (o *SendEmail) GetHtmlContent() string {
	if o == nil || IsNil(o.HtmlContent) {
		var ret string
		return ret
	}
	return *o.HtmlContent
}

// GetHtmlContentOk returns a tuple with the HtmlContent field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SendEmail) GetHtmlContentOk() (*string, bool) {
	if o == nil || IsNil(o.HtmlContent) {
		return nil, false
	}
	return o.HtmlContent, true
}

// HasHtmlContent returns a boolean if a field has been set.
func (o *SendEmail) HasHtmlContent() bool {
	if o != nil && !IsNil(o.HtmlContent) {
		return true
	}

	return false
}

// SetHtmlContent gets a reference to the given string and assigns it to the HtmlContent field.
func (o *SendEmail) SetHtmlContent(v string) {
	o.HtmlContent = &v
}

// GetMarkdownContent returns the MarkdownContent field value if set, zero value otherwise.
func (o *SendEmail) GetMarkdownContent() string {
	if o == nil || IsNil(o.MarkdownContent) {
		var ret string
		return ret
	}
	return *o.MarkdownContent
}

// GetMarkdownContentOk returns a tuple with the MarkdownContent field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SendEmail) GetMarkdownContentOk() (*string, bool) {
	if o == nil || IsNil(o.MarkdownContent) {
		return nil, false
	}
	return o.MarkdownContent, true
}

// HasMarkdownContent returns a boolean if a field has been set.
func (o *SendEmail) HasMarkdownContent() bool {
	if o != nil && !IsNil(o.MarkdownContent) {
		return true
	}

	return false
}

// SetMarkdownContent gets a reference to the given string and assigns it to the MarkdownContent field.
func (o *SendEmail) SetMarkdownContent(v string) {
	o.MarkdownContent = &v
}

// GetTemplateId returns the TemplateId field value if set, zero value otherwise.
func (o *SendEmail) GetTemplateId() string {
	if o == nil || IsNil(o.TemplateId) {
		var ret string
		return ret
	}
	return *o.TemplateId
}

// GetTemplateIdOk returns a tuple with the TemplateId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SendEmail) GetTemplateIdOk() (*string, bool) {
	if o == nil || IsNil(o.TemplateId) {
		return nil, false
	}
	return o.TemplateId, true
}

// HasTemplateId returns a boolean if a field has been set.
func (o *SendEmail) HasTemplateId() bool {
	if o != nil && !IsNil(o.TemplateId) {
		return true
	}

	return false
}

// SetTemplateId gets a reference to the given string and assigns it to the TemplateId field.
func (o *SendEmail) SetTemplateId(v string) {
	o.TemplateId = &v
}

// GetTemplateData returns the TemplateData field value if set, zero value otherwise.
func (o *SendEmail) GetTemplateData() map[string]interface{} {
	if o == nil || IsNil(o.TemplateData) {
		var ret map[string]interface{}
		return ret
	}
	return o.TemplateData
}

// GetTemplateDataOk returns a tuple with the TemplateData field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SendEmail) GetTemplateDataOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.TemplateData) {
		return map[string]interface{}{}, false
	}
	return o.TemplateData, true
}

// HasTemplateData returns a boolean if a field has been set.
func (o *SendEmail) HasTemplateData() bool {
	if o != nil && !IsNil(o.TemplateData) {
		return true
	}

	return false
}

// SetTemplateData gets a reference to the given map[string]interface{} and assigns it to the TemplateData field.
func (o *SendEmail) SetTemplateData(v map[string]interface{}) {
	o.TemplateData = v
}

// GetAttachments returns the Attachments field value if set, zero value otherwise.
func (o *SendEmail) GetAttachments() []Attachment {
	if o == nil || IsNil(o.Attachments) {
		var ret []Attachment
		return ret
	}
	return o.Attachments
}

// GetAttachmentsOk returns a tuple with the Attachments field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SendEmail) GetAttachmentsOk() ([]Attachment, bool) {
	if o == nil || IsNil(o.Attachments) {
		return nil, false
	}
	return o.Attachments, true
}

// HasAttachments returns a boolean if a field has been set.
func (o *SendEmail) HasAttachments() bool {
	if o != nil && !IsNil(o.Attachments) {
		return true
	}

	return false
}

// SetAttachments gets a reference to the given []Attachment and assigns it to the Attachments field.
func (o *SendEmail) SetAttachments(v []Attachment) {
	o.Attachments = v
}

// GetHeaders returns the Headers field value if set, zero value otherwise.
func (o *SendEmail) GetHeaders() map[string]string {
	if o == nil || IsNil(o.Headers) {
		var ret map[string]string
		return ret
	}
	return o.Headers
}

// GetHeadersOk returns a tuple with the Headers field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SendEmail) GetHeadersOk() (map[string]string, bool) {
	if o == nil || IsNil(o.Headers) {
		return map[string]string{}, false
	}
	return o.Headers, true
}

// HasHeaders returns a boolean if a field has been set.
func (o *SendEmail) HasHeaders() bool {
	if o != nil && !IsNil(o.Headers) {
		return true
	}

	return false
}

// SetHeaders gets a reference to the given map[string]string and assigns it to the Headers field.
func (o *SendEmail) SetHeaders(v map[string]string) {
	o.Headers = v
}

// GetReplyTo returns the ReplyTo field value if set, zero value otherwise.
func (o *SendEmail) GetReplyTo() Address {
	if o == nil || IsNil(o.ReplyTo) {
		var ret Address
		return ret
	}
	return *o.ReplyTo
}

// GetReplyToOk returns a tuple with the ReplyTo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SendEmail) GetReplyToOk() (*Address, bool) {
	if o == nil || IsNil(o.ReplyTo) {
		return nil, false
	}
	return o.ReplyTo, true
}

// HasReplyTo returns a boolean if a field has been set.
func (o *SendEmail) HasReplyTo() bool {
	if o != nil && !IsNil(o.ReplyTo) {
		return true
	}

	return false
}

// SetReplyTo gets a reference to the given Address and assigns it to the ReplyTo field.
func (o *SendEmail) SetReplyTo(v Address) {
	o.ReplyTo = &v
}

// GetSendTime returns the SendTime field value if set, zero value otherwise.
func (o *SendEmail) GetSendTime() int64 {
	if o == nil || IsNil(o.SendTime) {
		var ret int64
		return ret
	}
	return *o.SendTime
}

// GetSendTimeOk returns a tuple with the SendTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SendEmail) GetSendTimeOk() (*int64, bool) {
	if o == nil || IsNil(o.SendTime) {
		return nil, false
	}
	return o.SendTime, true
}

// HasSendTime returns a boolean if a field has been set.
func (o *SendEmail) HasSendTime() bool {
	if o != nil && !IsNil(o.SendTime) {
		return true
	}

	return false
}

// SetSendTime gets a reference to the given int64 and assigns it to the SendTime field.
func (o *SendEmail) SetSendTime(v int64) {
	o.SendTime = &v
}

// GetWebhookData returns the WebhookData field value if set, zero value otherwise.
func (o *SendEmail) GetWebhookData() map[string]string {
	if o == nil || IsNil(o.WebhookData) {
		var ret map[string]string
		return ret
	}
	return o.WebhookData
}

// GetWebhookDataOk returns a tuple with the WebhookData field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SendEmail) GetWebhookDataOk() (map[string]string, bool) {
	if o == nil || IsNil(o.WebhookData) {
		return map[string]string{}, false
	}
	return o.WebhookData, true
}

// HasWebhookData returns a boolean if a field has been set.
func (o *SendEmail) HasWebhookData() bool {
	if o != nil && !IsNil(o.WebhookData) {
		return true
	}

	return false
}

// SetWebhookData gets a reference to the given map[string]string and assigns it to the WebhookData field.
func (o *SendEmail) SetWebhookData(v map[string]string) {
	o.WebhookData = v
}

// GetTag returns the Tag field value if set, zero value otherwise.
func (o *SendEmail) GetTag() string {
	if o == nil || IsNil(o.Tag) {
		var ret string
		return ret
	}
	return *o.Tag
}

// GetTagOk returns a tuple with the Tag field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SendEmail) GetTagOk() (*string, bool) {
	if o == nil || IsNil(o.Tag) {
		return nil, false
	}
	return o.Tag, true
}

// HasTag returns a boolean if a field has been set.
func (o *SendEmail) HasTag() bool {
	if o != nil && !IsNil(o.Tag) {
		return true
	}

	return false
}

// SetTag gets a reference to the given string and assigns it to the Tag field.
func (o *SendEmail) SetTag(v string) {
	o.Tag = &v
}

// GetTracking returns the Tracking field value if set, zero value otherwise.
func (o *SendEmail) GetTracking() TrackingSettings {
	if o == nil || IsNil(o.Tracking) {
		var ret TrackingSettings
		return ret
	}
	return *o.Tracking
}

// GetTrackingOk returns a tuple with the Tracking field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SendEmail) GetTrackingOk() (*TrackingSettings, bool) {
	if o == nil || IsNil(o.Tracking) {
		return nil, false
	}
	return o.Tracking, true
}

// HasTracking returns a boolean if a field has been set.
func (o *SendEmail) HasTracking() bool {
	if o != nil && !IsNil(o.Tracking) {
		return true
	}

	return false
}

// SetTracking gets a reference to the given TrackingSettings and assigns it to the Tracking field.
func (o *SendEmail) SetTracking(v TrackingSettings) {
	o.Tracking = &v
}

func (o SendEmail) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SendEmail) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["from"] = o.From
	toSerialize["to"] = o.To
	toSerialize["subject"] = o.Subject
	if !IsNil(o.TextContent) {
		toSerialize["text_content"] = o.TextContent
	}
	if !IsNil(o.HtmlContent) {
		toSerialize["html_content"] = o.HtmlContent
	}
	if !IsNil(o.MarkdownContent) {
		toSerialize["markdown_content"] = o.MarkdownContent
	}
	if !IsNil(o.TemplateId) {
		toSerialize["template_id"] = o.TemplateId
	}
	if !IsNil(o.TemplateData) {
		toSerialize["template_data"] = o.TemplateData
	}
	if !IsNil(o.Attachments) {
		toSerialize["attachments"] = o.Attachments
	}
	if !IsNil(o.Headers) {
		toSerialize["headers"] = o.Headers
	}
	if !IsNil(o.ReplyTo) {
		toSerialize["reply_to"] = o.ReplyTo
	}
	if !IsNil(o.SendTime) {
		toSerialize["send_time"] = o.SendTime
	}
	if !IsNil(o.WebhookData) {
		toSerialize["webhook_data"] = o.WebhookData
	}
	if !IsNil(o.Tag) {
		toSerialize["tag"] = o.Tag
	}
	if !IsNil(o.Tracking) {
		toSerialize["tracking"] = o.Tracking
	}
	return toSerialize, nil
}

func (o *SendEmail) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"from",
		"to",
		"subject",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSendEmail := _SendEmail{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSendEmail)

	if err != nil {
		return err
	}

	*o = SendEmail(varSendEmail)

	return err
}

type NullableSendEmail struct {
	value *SendEmail
	isSet bool
}

func (v NullableSendEmail) Get() *SendEmail {
	return v.value
}

func (v *NullableSendEmail) Set(val *SendEmail) {
	v.value = val
	v.isSet = true
}

func (v NullableSendEmail) IsSet() bool {
	return v.isSet
}

func (v *NullableSendEmail) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSendEmail(val *SendEmail) *NullableSendEmail {
	return &NullableSendEmail{value: val, isSet: true}
}

func (v NullableSendEmail) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSendEmail) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


