/*
Goodsender API

Goodsender API. ### Authorization  All API requests require an API key in the `Authorization` header:  ``` Authorization: Bearer <your-api-key> ``` 

API version: 1.0.0
Contact: support@goodsender.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package goodsender

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SendEmailErrorResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SendEmailErrorResponse{}

// SendEmailErrorResponse struct for SendEmailErrorResponse
type SendEmailErrorResponse struct {
	// Error message
	Error string `json:"error"`
}

type _SendEmailErrorResponse SendEmailErrorResponse

// NewSendEmailErrorResponse instantiates a new SendEmailErrorResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSendEmailErrorResponse(error_ string) *SendEmailErrorResponse {
	this := SendEmailErrorResponse{}
	this.Error = error_
	return &this
}

// NewSendEmailErrorResponseWithDefaults instantiates a new SendEmailErrorResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSendEmailErrorResponseWithDefaults() *SendEmailErrorResponse {
	this := SendEmailErrorResponse{}
	return &this
}

// GetError returns the Error field value
func (o *SendEmailErrorResponse) GetError() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Error
}

// GetErrorOk returns a tuple with the Error field value
// and a boolean to check if the value has been set.
func (o *SendEmailErrorResponse) GetErrorOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Error, true
}

// SetError sets field value
func (o *SendEmailErrorResponse) SetError(v string) {
	o.Error = v
}

func (o SendEmailErrorResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SendEmailErrorResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["error"] = o.Error
	return toSerialize, nil
}

func (o *SendEmailErrorResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"error",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSendEmailErrorResponse := _SendEmailErrorResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSendEmailErrorResponse)

	if err != nil {
		return err
	}

	*o = SendEmailErrorResponse(varSendEmailErrorResponse)

	return err
}

type NullableSendEmailErrorResponse struct {
	value *SendEmailErrorResponse
	isSet bool
}

func (v NullableSendEmailErrorResponse) Get() *SendEmailErrorResponse {
	return v.value
}

func (v *NullableSendEmailErrorResponse) Set(val *SendEmailErrorResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableSendEmailErrorResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableSendEmailErrorResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSendEmailErrorResponse(val *SendEmailErrorResponse) *NullableSendEmailErrorResponse {
	return &NullableSendEmailErrorResponse{value: val, isSet: true}
}

func (v NullableSendEmailErrorResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSendEmailErrorResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


