/*
Goodsender API

Goodsender API. ### Authorization  All API requests require an API key in the `Authorization` header:  ``` Authorization: Bearer <your-api-key> ``` 

API version: 1.0.0
Contact: support@goodsender.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package goodsender

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the TemplateEmailRequestTemplate type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TemplateEmailRequestTemplate{}

// TemplateEmailRequestTemplate struct for TemplateEmailRequestTemplate
type TemplateEmailRequestTemplate struct {
	// The ID of the template to use
	TemplateId string `json:"template_id"`
	// Key-value pairs to populate template variables
	Variables map[string]string `json:"variables,omitempty"`
}

type _TemplateEmailRequestTemplate TemplateEmailRequestTemplate

// NewTemplateEmailRequestTemplate instantiates a new TemplateEmailRequestTemplate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTemplateEmailRequestTemplate(templateId string) *TemplateEmailRequestTemplate {
	this := TemplateEmailRequestTemplate{}
	this.TemplateId = templateId
	return &this
}

// NewTemplateEmailRequestTemplateWithDefaults instantiates a new TemplateEmailRequestTemplate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTemplateEmailRequestTemplateWithDefaults() *TemplateEmailRequestTemplate {
	this := TemplateEmailRequestTemplate{}
	return &this
}

// GetTemplateId returns the TemplateId field value
func (o *TemplateEmailRequestTemplate) GetTemplateId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.TemplateId
}

// GetTemplateIdOk returns a tuple with the TemplateId field value
// and a boolean to check if the value has been set.
func (o *TemplateEmailRequestTemplate) GetTemplateIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TemplateId, true
}

// SetTemplateId sets field value
func (o *TemplateEmailRequestTemplate) SetTemplateId(v string) {
	o.TemplateId = v
}

// GetVariables returns the Variables field value if set, zero value otherwise.
func (o *TemplateEmailRequestTemplate) GetVariables() map[string]string {
	if o == nil || IsNil(o.Variables) {
		var ret map[string]string
		return ret
	}
	return o.Variables
}

// GetVariablesOk returns a tuple with the Variables field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TemplateEmailRequestTemplate) GetVariablesOk() (map[string]string, bool) {
	if o == nil || IsNil(o.Variables) {
		return map[string]string{}, false
	}
	return o.Variables, true
}

// HasVariables returns a boolean if a field has been set.
func (o *TemplateEmailRequestTemplate) HasVariables() bool {
	if o != nil && !IsNil(o.Variables) {
		return true
	}

	return false
}

// SetVariables gets a reference to the given map[string]string and assigns it to the Variables field.
func (o *TemplateEmailRequestTemplate) SetVariables(v map[string]string) {
	o.Variables = v
}

func (o TemplateEmailRequestTemplate) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TemplateEmailRequestTemplate) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["template_id"] = o.TemplateId
	if !IsNil(o.Variables) {
		toSerialize["variables"] = o.Variables
	}
	return toSerialize, nil
}

func (o *TemplateEmailRequestTemplate) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"template_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTemplateEmailRequestTemplate := _TemplateEmailRequestTemplate{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varTemplateEmailRequestTemplate)

	if err != nil {
		return err
	}

	*o = TemplateEmailRequestTemplate(varTemplateEmailRequestTemplate)

	return err
}

type NullableTemplateEmailRequestTemplate struct {
	value *TemplateEmailRequestTemplate
	isSet bool
}

func (v NullableTemplateEmailRequestTemplate) Get() *TemplateEmailRequestTemplate {
	return v.value
}

func (v *NullableTemplateEmailRequestTemplate) Set(val *TemplateEmailRequestTemplate) {
	v.value = val
	v.isSet = true
}

func (v NullableTemplateEmailRequestTemplate) IsSet() bool {
	return v.isSet
}

func (v *NullableTemplateEmailRequestTemplate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTemplateEmailRequestTemplate(val *TemplateEmailRequestTemplate) *NullableTemplateEmailRequestTemplate {
	return &NullableTemplateEmailRequestTemplate{value: val, isSet: true}
}

func (v NullableTemplateEmailRequestTemplate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTemplateEmailRequestTemplate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


