/*
Goodsender API

Goodsender API. ### Authorization  All API requests require an API key in the `Authorization` header:  ``` Authorization: Bearer <your-api-key> ``` 

API version: 1.0.0
Contact: support@goodsender.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package goodsender

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the EmailAccount type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EmailAccount{}

// EmailAccount struct for EmailAccount
type EmailAccount struct {
	// Recipient email address.
	Email string `json:"email"`
	// Optional display name for the recipient. Used in the To header on the consent email when present, and surfaced through the Dashboard. May be null when no name has been provided.
	Name NullableString `json:"name,omitempty"`
	// Domain part of the email address.
	Domain string `json:"domain"`
	// Status of the recipient's consent for receiving emails. 'pending' = awaiting consent email send, 'requested' = consent email dispatched, 'failed' = consent email delivery failed, 'granted' = recipient consented to receive emails, 'denied' = recipient declined to receive emails.
	ConsentStatus string `json:"consentStatus"`
	// Status of the recipient's engagement with the emails.
	EngagementStatus *string `json:"engagementStatus,omitempty"`
}

type _EmailAccount EmailAccount

// NewEmailAccount instantiates a new EmailAccount object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEmailAccount(email string, domain string, consentStatus string) *EmailAccount {
	this := EmailAccount{}
	this.Email = email
	this.Domain = domain
	this.ConsentStatus = consentStatus
	return &this
}

// NewEmailAccountWithDefaults instantiates a new EmailAccount object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEmailAccountWithDefaults() *EmailAccount {
	this := EmailAccount{}
	return &this
}

// GetEmail returns the Email field value
func (o *EmailAccount) GetEmail() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Email
}

// GetEmailOk returns a tuple with the Email field value
// and a boolean to check if the value has been set.
func (o *EmailAccount) GetEmailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Email, true
}

// SetEmail sets field value
func (o *EmailAccount) SetEmail(v string) {
	o.Email = v
}

// GetName returns the Name field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *EmailAccount) GetName() string {
	if o == nil || IsNil(o.Name.Get()) {
		var ret string
		return ret
	}
	return *o.Name.Get()
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *EmailAccount) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Name.Get(), o.Name.IsSet()
}

// HasName returns a boolean if a field has been set.
func (o *EmailAccount) HasName() bool {
	if o != nil && o.Name.IsSet() {
		return true
	}

	return false
}

// SetName gets a reference to the given NullableString and assigns it to the Name field.
func (o *EmailAccount) SetName(v string) {
	o.Name.Set(&v)
}
// SetNameNil sets the value for Name to be an explicit nil
func (o *EmailAccount) SetNameNil() {
	o.Name.Set(nil)
}

// UnsetName ensures that no value is present for Name, not even an explicit nil
func (o *EmailAccount) UnsetName() {
	o.Name.Unset()
}

// GetDomain returns the Domain field value
func (o *EmailAccount) GetDomain() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Domain
}

// GetDomainOk returns a tuple with the Domain field value
// and a boolean to check if the value has been set.
func (o *EmailAccount) GetDomainOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Domain, true
}

// SetDomain sets field value
func (o *EmailAccount) SetDomain(v string) {
	o.Domain = v
}

// GetConsentStatus returns the ConsentStatus field value
func (o *EmailAccount) GetConsentStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ConsentStatus
}

// GetConsentStatusOk returns a tuple with the ConsentStatus field value
// and a boolean to check if the value has been set.
func (o *EmailAccount) GetConsentStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ConsentStatus, true
}

// SetConsentStatus sets field value
func (o *EmailAccount) SetConsentStatus(v string) {
	o.ConsentStatus = v
}

// GetEngagementStatus returns the EngagementStatus field value if set, zero value otherwise.
func (o *EmailAccount) GetEngagementStatus() string {
	if o == nil || IsNil(o.EngagementStatus) {
		var ret string
		return ret
	}
	return *o.EngagementStatus
}

// GetEngagementStatusOk returns a tuple with the EngagementStatus field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EmailAccount) GetEngagementStatusOk() (*string, bool) {
	if o == nil || IsNil(o.EngagementStatus) {
		return nil, false
	}
	return o.EngagementStatus, true
}

// HasEngagementStatus returns a boolean if a field has been set.
func (o *EmailAccount) HasEngagementStatus() bool {
	if o != nil && !IsNil(o.EngagementStatus) {
		return true
	}

	return false
}

// SetEngagementStatus gets a reference to the given string and assigns it to the EngagementStatus field.
func (o *EmailAccount) SetEngagementStatus(v string) {
	o.EngagementStatus = &v
}

func (o EmailAccount) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EmailAccount) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["email"] = o.Email
	if o.Name.IsSet() {
		toSerialize["name"] = o.Name.Get()
	}
	toSerialize["domain"] = o.Domain
	toSerialize["consentStatus"] = o.ConsentStatus
	if !IsNil(o.EngagementStatus) {
		toSerialize["engagementStatus"] = o.EngagementStatus
	}
	return toSerialize, nil
}

func (o *EmailAccount) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"email",
		"domain",
		"consentStatus",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varEmailAccount := _EmailAccount{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varEmailAccount)

	if err != nil {
		return err
	}

	*o = EmailAccount(varEmailAccount)

	return err
}

type NullableEmailAccount struct {
	value *EmailAccount
	isSet bool
}

func (v NullableEmailAccount) Get() *EmailAccount {
	return v.value
}

func (v *NullableEmailAccount) Set(val *EmailAccount) {
	v.value = val
	v.isSet = true
}

func (v NullableEmailAccount) IsSet() bool {
	return v.isSet
}

func (v *NullableEmailAccount) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEmailAccount(val *EmailAccount) *NullableEmailAccount {
	return &NullableEmailAccount{value: val, isSet: true}
}

func (v NullableEmailAccount) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEmailAccount) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


