/*
Goodsender API

Goodsender API. ### Authorization  All API requests require an API key in the `Authorization` header:  ``` Authorization: Bearer <your-api-key> ``` 

API version: 1.0.0
Contact: support@goodsender.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package goodsender

import (
	"encoding/json"
)

// checks if the TrackingSettings type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TrackingSettings{}

// TrackingSettings Controls email tracking and unsubscribe settings
type TrackingSettings struct {
	// Whether to track email opens
	Opens *bool `json:"opens,omitempty"`
	// Whether to track link clicks
	Clicks *bool `json:"clicks,omitempty"`
	// Whether to track unsubscribes
	Unsubscribes *bool `json:"unsubscribes,omitempty"`
	// Optional unsubscribe group ID. If not specified, uses global unsubscribe list. This setting is ignored if unsubscribes is false.
	UnsubscribeGroupId NullableInt64 `json:"unsubscribe_group_id,omitempty"`
}

// NewTrackingSettings instantiates a new TrackingSettings object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTrackingSettings() *TrackingSettings {
	this := TrackingSettings{}
	return &this
}

// NewTrackingSettingsWithDefaults instantiates a new TrackingSettings object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTrackingSettingsWithDefaults() *TrackingSettings {
	this := TrackingSettings{}
	return &this
}

// GetOpens returns the Opens field value if set, zero value otherwise.
func (o *TrackingSettings) GetOpens() bool {
	if o == nil || IsNil(o.Opens) {
		var ret bool
		return ret
	}
	return *o.Opens
}

// GetOpensOk returns a tuple with the Opens field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TrackingSettings) GetOpensOk() (*bool, bool) {
	if o == nil || IsNil(o.Opens) {
		return nil, false
	}
	return o.Opens, true
}

// HasOpens returns a boolean if a field has been set.
func (o *TrackingSettings) HasOpens() bool {
	if o != nil && !IsNil(o.Opens) {
		return true
	}

	return false
}

// SetOpens gets a reference to the given bool and assigns it to the Opens field.
func (o *TrackingSettings) SetOpens(v bool) {
	o.Opens = &v
}

// GetClicks returns the Clicks field value if set, zero value otherwise.
func (o *TrackingSettings) GetClicks() bool {
	if o == nil || IsNil(o.Clicks) {
		var ret bool
		return ret
	}
	return *o.Clicks
}

// GetClicksOk returns a tuple with the Clicks field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TrackingSettings) GetClicksOk() (*bool, bool) {
	if o == nil || IsNil(o.Clicks) {
		return nil, false
	}
	return o.Clicks, true
}

// HasClicks returns a boolean if a field has been set.
func (o *TrackingSettings) HasClicks() bool {
	if o != nil && !IsNil(o.Clicks) {
		return true
	}

	return false
}

// SetClicks gets a reference to the given bool and assigns it to the Clicks field.
func (o *TrackingSettings) SetClicks(v bool) {
	o.Clicks = &v
}

// GetUnsubscribes returns the Unsubscribes field value if set, zero value otherwise.
func (o *TrackingSettings) GetUnsubscribes() bool {
	if o == nil || IsNil(o.Unsubscribes) {
		var ret bool
		return ret
	}
	return *o.Unsubscribes
}

// GetUnsubscribesOk returns a tuple with the Unsubscribes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TrackingSettings) GetUnsubscribesOk() (*bool, bool) {
	if o == nil || IsNil(o.Unsubscribes) {
		return nil, false
	}
	return o.Unsubscribes, true
}

// HasUnsubscribes returns a boolean if a field has been set.
func (o *TrackingSettings) HasUnsubscribes() bool {
	if o != nil && !IsNil(o.Unsubscribes) {
		return true
	}

	return false
}

// SetUnsubscribes gets a reference to the given bool and assigns it to the Unsubscribes field.
func (o *TrackingSettings) SetUnsubscribes(v bool) {
	o.Unsubscribes = &v
}

// GetUnsubscribeGroupId returns the UnsubscribeGroupId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *TrackingSettings) GetUnsubscribeGroupId() int64 {
	if o == nil || IsNil(o.UnsubscribeGroupId.Get()) {
		var ret int64
		return ret
	}
	return *o.UnsubscribeGroupId.Get()
}

// GetUnsubscribeGroupIdOk returns a tuple with the UnsubscribeGroupId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *TrackingSettings) GetUnsubscribeGroupIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return o.UnsubscribeGroupId.Get(), o.UnsubscribeGroupId.IsSet()
}

// HasUnsubscribeGroupId returns a boolean if a field has been set.
func (o *TrackingSettings) HasUnsubscribeGroupId() bool {
	if o != nil && o.UnsubscribeGroupId.IsSet() {
		return true
	}

	return false
}

// SetUnsubscribeGroupId gets a reference to the given NullableInt64 and assigns it to the UnsubscribeGroupId field.
func (o *TrackingSettings) SetUnsubscribeGroupId(v int64) {
	o.UnsubscribeGroupId.Set(&v)
}
// SetUnsubscribeGroupIdNil sets the value for UnsubscribeGroupId to be an explicit nil
func (o *TrackingSettings) SetUnsubscribeGroupIdNil() {
	o.UnsubscribeGroupId.Set(nil)
}

// UnsetUnsubscribeGroupId ensures that no value is present for UnsubscribeGroupId, not even an explicit nil
func (o *TrackingSettings) UnsetUnsubscribeGroupId() {
	o.UnsubscribeGroupId.Unset()
}

func (o TrackingSettings) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TrackingSettings) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Opens) {
		toSerialize["opens"] = o.Opens
	}
	if !IsNil(o.Clicks) {
		toSerialize["clicks"] = o.Clicks
	}
	if !IsNil(o.Unsubscribes) {
		toSerialize["unsubscribes"] = o.Unsubscribes
	}
	if o.UnsubscribeGroupId.IsSet() {
		toSerialize["unsubscribe_group_id"] = o.UnsubscribeGroupId.Get()
	}
	return toSerialize, nil
}

type NullableTrackingSettings struct {
	value *TrackingSettings
	isSet bool
}

func (v NullableTrackingSettings) Get() *TrackingSettings {
	return v.value
}

func (v *NullableTrackingSettings) Set(val *TrackingSettings) {
	v.value = val
	v.isSet = true
}

func (v NullableTrackingSettings) IsSet() bool {
	return v.isSet
}

func (v *NullableTrackingSettings) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTrackingSettings(val *TrackingSettings) *NullableTrackingSettings {
	return &NullableTrackingSettings{value: val, isSet: true}
}

func (v NullableTrackingSettings) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTrackingSettings) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


