/*
Goodsender API

Goodsender API. ### Authorization  All API requests require an API key in the `Authorization` header:  ``` Authorization: Bearer <your-api-key> ``` 

API version: 1.0.0
Contact: support@goodsender.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package goodsender

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the QuotaExceededError type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &QuotaExceededError{}

// QuotaExceededError struct for QuotaExceededError
type QuotaExceededError struct {
	// Machine-readable error code.
	Code string `json:"code"`
	// Whether the daily or monthly quota was exhausted.
	Kind string `json:"kind"`
	// Human-readable error message.
	Message string `json:"message"`
	// Quota limit that was reached.
	Limit int32 `json:"limit"`
	// Number of emails already used against the quota.
	Used int32 `json:"used"`
	// Timestamp at which the quota window resets.
	ResetAt time.Time `json:"resetAt"`
}

type _QuotaExceededError QuotaExceededError

// NewQuotaExceededError instantiates a new QuotaExceededError object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewQuotaExceededError(code string, kind string, message string, limit int32, used int32, resetAt time.Time) *QuotaExceededError {
	this := QuotaExceededError{}
	this.Code = code
	this.Kind = kind
	this.Message = message
	this.Limit = limit
	this.Used = used
	this.ResetAt = resetAt
	return &this
}

// NewQuotaExceededErrorWithDefaults instantiates a new QuotaExceededError object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewQuotaExceededErrorWithDefaults() *QuotaExceededError {
	this := QuotaExceededError{}
	return &this
}

// GetCode returns the Code field value
func (o *QuotaExceededError) GetCode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Code
}

// GetCodeOk returns a tuple with the Code field value
// and a boolean to check if the value has been set.
func (o *QuotaExceededError) GetCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Code, true
}

// SetCode sets field value
func (o *QuotaExceededError) SetCode(v string) {
	o.Code = v
}

// GetKind returns the Kind field value
func (o *QuotaExceededError) GetKind() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Kind
}

// GetKindOk returns a tuple with the Kind field value
// and a boolean to check if the value has been set.
func (o *QuotaExceededError) GetKindOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Kind, true
}

// SetKind sets field value
func (o *QuotaExceededError) SetKind(v string) {
	o.Kind = v
}

// GetMessage returns the Message field value
func (o *QuotaExceededError) GetMessage() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Message
}

// GetMessageOk returns a tuple with the Message field value
// and a boolean to check if the value has been set.
func (o *QuotaExceededError) GetMessageOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Message, true
}

// SetMessage sets field value
func (o *QuotaExceededError) SetMessage(v string) {
	o.Message = v
}

// GetLimit returns the Limit field value
func (o *QuotaExceededError) GetLimit() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Limit
}

// GetLimitOk returns a tuple with the Limit field value
// and a boolean to check if the value has been set.
func (o *QuotaExceededError) GetLimitOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Limit, true
}

// SetLimit sets field value
func (o *QuotaExceededError) SetLimit(v int32) {
	o.Limit = v
}

// GetUsed returns the Used field value
func (o *QuotaExceededError) GetUsed() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Used
}

// GetUsedOk returns a tuple with the Used field value
// and a boolean to check if the value has been set.
func (o *QuotaExceededError) GetUsedOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Used, true
}

// SetUsed sets field value
func (o *QuotaExceededError) SetUsed(v int32) {
	o.Used = v
}

// GetResetAt returns the ResetAt field value
func (o *QuotaExceededError) GetResetAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.ResetAt
}

// GetResetAtOk returns a tuple with the ResetAt field value
// and a boolean to check if the value has been set.
func (o *QuotaExceededError) GetResetAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ResetAt, true
}

// SetResetAt sets field value
func (o *QuotaExceededError) SetResetAt(v time.Time) {
	o.ResetAt = v
}

func (o QuotaExceededError) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o QuotaExceededError) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["code"] = o.Code
	toSerialize["kind"] = o.Kind
	toSerialize["message"] = o.Message
	toSerialize["limit"] = o.Limit
	toSerialize["used"] = o.Used
	toSerialize["resetAt"] = o.ResetAt
	return toSerialize, nil
}

func (o *QuotaExceededError) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"code",
		"kind",
		"message",
		"limit",
		"used",
		"resetAt",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varQuotaExceededError := _QuotaExceededError{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varQuotaExceededError)

	if err != nil {
		return err
	}

	*o = QuotaExceededError(varQuotaExceededError)

	return err
}

type NullableQuotaExceededError struct {
	value *QuotaExceededError
	isSet bool
}

func (v NullableQuotaExceededError) Get() *QuotaExceededError {
	return v.value
}

func (v *NullableQuotaExceededError) Set(val *QuotaExceededError) {
	v.value = val
	v.isSet = true
}

func (v NullableQuotaExceededError) IsSet() bool {
	return v.isSet
}

func (v *NullableQuotaExceededError) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableQuotaExceededError(val *QuotaExceededError) *NullableQuotaExceededError {
	return &NullableQuotaExceededError{value: val, isSet: true}
}

func (v NullableQuotaExceededError) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableQuotaExceededError) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


