/*
Goodsender API

Goodsender API. ### Authorization  All API requests require an API key in the `Authorization` header:  ``` Authorization: Bearer <your-api-key> ``` 

API version: 1.0.0
Contact: support@goodsender.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package goodsender

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the SendEmailRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SendEmailRequest{}

// SendEmailRequest struct for SendEmailRequest
type SendEmailRequest struct {
	// List of emails to send. Cannot be empty.
	Emails []SendEmail `json:"emails"`
}

type _SendEmailRequest SendEmailRequest

// NewSendEmailRequest instantiates a new SendEmailRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSendEmailRequest(emails []SendEmail) *SendEmailRequest {
	this := SendEmailRequest{}
	this.Emails = emails
	return &this
}

// NewSendEmailRequestWithDefaults instantiates a new SendEmailRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSendEmailRequestWithDefaults() *SendEmailRequest {
	this := SendEmailRequest{}
	return &this
}

// GetEmails returns the Emails field value
func (o *SendEmailRequest) GetEmails() []SendEmail {
	if o == nil {
		var ret []SendEmail
		return ret
	}

	return o.Emails
}

// GetEmailsOk returns a tuple with the Emails field value
// and a boolean to check if the value has been set.
func (o *SendEmailRequest) GetEmailsOk() ([]SendEmail, bool) {
	if o == nil {
		return nil, false
	}
	return o.Emails, true
}

// SetEmails sets field value
func (o *SendEmailRequest) SetEmails(v []SendEmail) {
	o.Emails = v
}

func (o SendEmailRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SendEmailRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["emails"] = o.Emails
	return toSerialize, nil
}

func (o *SendEmailRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"emails",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varSendEmailRequest := _SendEmailRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varSendEmailRequest)

	if err != nil {
		return err
	}

	*o = SendEmailRequest(varSendEmailRequest)

	return err
}

type NullableSendEmailRequest struct {
	value *SendEmailRequest
	isSet bool
}

func (v NullableSendEmailRequest) Get() *SendEmailRequest {
	return v.value
}

func (v *NullableSendEmailRequest) Set(val *SendEmailRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableSendEmailRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableSendEmailRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSendEmailRequest(val *SendEmailRequest) *NullableSendEmailRequest {
	return &NullableSendEmailRequest{value: val, isSet: true}
}

func (v NullableSendEmailRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSendEmailRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


