/*
Goodsender API

Goodsender API. ### Authorization  All API requests require an API key in the `Authorization` header:  ``` Authorization: Bearer <your-api-key> ``` 

API version: 1.0.0
Contact: support@goodsender.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package goodsender

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the DomainVerification type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DomainVerification{}

// DomainVerification Per-record verification state for the domain. `verified` is the overall flag; the individual `*_verified` fields indicate which DNS records still need attention when `verified` is `false`. 
type DomainVerification struct {
	// Overall verification status. True only when every required DNS record is in place.
	Verified bool `json:"verified"`
	// Whether the tracking subdomain CNAME is in place.
	TrackingVerified bool `json:"tracking_verified"`
	// Whether the return-path subdomain CNAME is in place.
	ReturnPathVerified bool `json:"return_path_verified"`
	// Whether the first DKIM record is in place.
	Dkim1Verified bool `json:"dkim1_verified"`
	// Whether the second DKIM record is in place.
	Dkim2Verified bool `json:"dkim2_verified"`
}

type _DomainVerification DomainVerification

// NewDomainVerification instantiates a new DomainVerification object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDomainVerification(verified bool, trackingVerified bool, returnPathVerified bool, dkim1Verified bool, dkim2Verified bool) *DomainVerification {
	this := DomainVerification{}
	this.Verified = verified
	this.TrackingVerified = trackingVerified
	this.ReturnPathVerified = returnPathVerified
	this.Dkim1Verified = dkim1Verified
	this.Dkim2Verified = dkim2Verified
	return &this
}

// NewDomainVerificationWithDefaults instantiates a new DomainVerification object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDomainVerificationWithDefaults() *DomainVerification {
	this := DomainVerification{}
	return &this
}

// GetVerified returns the Verified field value
func (o *DomainVerification) GetVerified() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Verified
}

// GetVerifiedOk returns a tuple with the Verified field value
// and a boolean to check if the value has been set.
func (o *DomainVerification) GetVerifiedOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Verified, true
}

// SetVerified sets field value
func (o *DomainVerification) SetVerified(v bool) {
	o.Verified = v
}

// GetTrackingVerified returns the TrackingVerified field value
func (o *DomainVerification) GetTrackingVerified() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.TrackingVerified
}

// GetTrackingVerifiedOk returns a tuple with the TrackingVerified field value
// and a boolean to check if the value has been set.
func (o *DomainVerification) GetTrackingVerifiedOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TrackingVerified, true
}

// SetTrackingVerified sets field value
func (o *DomainVerification) SetTrackingVerified(v bool) {
	o.TrackingVerified = v
}

// GetReturnPathVerified returns the ReturnPathVerified field value
func (o *DomainVerification) GetReturnPathVerified() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.ReturnPathVerified
}

// GetReturnPathVerifiedOk returns a tuple with the ReturnPathVerified field value
// and a boolean to check if the value has been set.
func (o *DomainVerification) GetReturnPathVerifiedOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ReturnPathVerified, true
}

// SetReturnPathVerified sets field value
func (o *DomainVerification) SetReturnPathVerified(v bool) {
	o.ReturnPathVerified = v
}

// GetDkim1Verified returns the Dkim1Verified field value
func (o *DomainVerification) GetDkim1Verified() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Dkim1Verified
}

// GetDkim1VerifiedOk returns a tuple with the Dkim1Verified field value
// and a boolean to check if the value has been set.
func (o *DomainVerification) GetDkim1VerifiedOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Dkim1Verified, true
}

// SetDkim1Verified sets field value
func (o *DomainVerification) SetDkim1Verified(v bool) {
	o.Dkim1Verified = v
}

// GetDkim2Verified returns the Dkim2Verified field value
func (o *DomainVerification) GetDkim2Verified() bool {
	if o == nil {
		var ret bool
		return ret
	}

	return o.Dkim2Verified
}

// GetDkim2VerifiedOk returns a tuple with the Dkim2Verified field value
// and a boolean to check if the value has been set.
func (o *DomainVerification) GetDkim2VerifiedOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Dkim2Verified, true
}

// SetDkim2Verified sets field value
func (o *DomainVerification) SetDkim2Verified(v bool) {
	o.Dkim2Verified = v
}

func (o DomainVerification) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DomainVerification) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["verified"] = o.Verified
	toSerialize["tracking_verified"] = o.TrackingVerified
	toSerialize["return_path_verified"] = o.ReturnPathVerified
	toSerialize["dkim1_verified"] = o.Dkim1Verified
	toSerialize["dkim2_verified"] = o.Dkim2Verified
	return toSerialize, nil
}

func (o *DomainVerification) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"verified",
		"tracking_verified",
		"return_path_verified",
		"dkim1_verified",
		"dkim2_verified",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDomainVerification := _DomainVerification{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDomainVerification)

	if err != nil {
		return err
	}

	*o = DomainVerification(varDomainVerification)

	return err
}

type NullableDomainVerification struct {
	value *DomainVerification
	isSet bool
}

func (v NullableDomainVerification) Get() *DomainVerification {
	return v.value
}

func (v *NullableDomainVerification) Set(val *DomainVerification) {
	v.value = val
	v.isSet = true
}

func (v NullableDomainVerification) IsSet() bool {
	return v.isSet
}

func (v *NullableDomainVerification) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDomainVerification(val *DomainVerification) *NullableDomainVerification {
	return &NullableDomainVerification{value: val, isSet: true}
}

func (v NullableDomainVerification) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDomainVerification) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


