/*
Goodsender API

Goodsender API. ### Authorization  All API requests require an API key in the `Authorization` header:  ``` Authorization: Bearer <your-api-key> ``` 

API version: 1.0.0
Contact: support@goodsender.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package goodsender

import (
	"encoding/json"
	"fmt"
	"gopkg.in/validator.v2"
)

// ConsentEmailEntry - Single entry in the `emails` array of a consent request. Either a bare email string (back-compat) or a `{ email, name? }` object so callers can attach a display name to a specific recipient. 
type ConsentEmailEntry struct {
	ConsentEmailRecipient *ConsentEmailRecipient
	String *string
}

// ConsentEmailRecipientAsConsentEmailEntry is a convenience function that returns ConsentEmailRecipient wrapped in ConsentEmailEntry
func ConsentEmailRecipientAsConsentEmailEntry(v *ConsentEmailRecipient) ConsentEmailEntry {
	return ConsentEmailEntry{
		ConsentEmailRecipient: v,
	}
}

// stringAsConsentEmailEntry is a convenience function that returns string wrapped in ConsentEmailEntry
func StringAsConsentEmailEntry(v *string) ConsentEmailEntry {
	return ConsentEmailEntry{
		String: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *ConsentEmailEntry) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into ConsentEmailRecipient
	err = newStrictDecoder(data).Decode(&dst.ConsentEmailRecipient)
	if err == nil {
		jsonConsentEmailRecipient, _ := json.Marshal(dst.ConsentEmailRecipient)
		if string(jsonConsentEmailRecipient) == "{}" { // empty struct
			dst.ConsentEmailRecipient = nil
		} else {
			if err = validator.Validate(dst.ConsentEmailRecipient); err != nil {
				dst.ConsentEmailRecipient = nil
			} else {
				match++
			}
		}
	} else {
		dst.ConsentEmailRecipient = nil
	}

	// try to unmarshal data into String
	err = newStrictDecoder(data).Decode(&dst.String)
	if err == nil {
		jsonString, _ := json.Marshal(dst.String)
		if string(jsonString) == "{}" { // empty struct
			dst.String = nil
		} else {
			if err = validator.Validate(dst.String); err != nil {
				dst.String = nil
			} else {
				match++
			}
		}
	} else {
		dst.String = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.ConsentEmailRecipient = nil
		dst.String = nil

		return fmt.Errorf("data matches more than one schema in oneOf(ConsentEmailEntry)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(ConsentEmailEntry)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src ConsentEmailEntry) MarshalJSON() ([]byte, error) {
	if src.ConsentEmailRecipient != nil {
		return json.Marshal(&src.ConsentEmailRecipient)
	}

	if src.String != nil {
		return json.Marshal(&src.String)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *ConsentEmailEntry) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.ConsentEmailRecipient != nil {
		return obj.ConsentEmailRecipient
	}

	if obj.String != nil {
		return obj.String
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj ConsentEmailEntry) GetActualInstanceValue() (interface{}) {
	if obj.ConsentEmailRecipient != nil {
		return *obj.ConsentEmailRecipient
	}

	if obj.String != nil {
		return *obj.String
	}

	// all schemas are nil
	return nil
}

type NullableConsentEmailEntry struct {
	value *ConsentEmailEntry
	isSet bool
}

func (v NullableConsentEmailEntry) Get() *ConsentEmailEntry {
	return v.value
}

func (v *NullableConsentEmailEntry) Set(val *ConsentEmailEntry) {
	v.value = val
	v.isSet = true
}

func (v NullableConsentEmailEntry) IsSet() bool {
	return v.isSet
}

func (v *NullableConsentEmailEntry) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableConsentEmailEntry(val *ConsentEmailEntry) *NullableConsentEmailEntry {
	return &NullableConsentEmailEntry{value: val, isSet: true}
}

func (v NullableConsentEmailEntry) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableConsentEmailEntry) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


